✨ Implement Image Upload
woowacourse-teams/2024-pengcook pull request #137
Opened 2024-08-01 06:57 UTC by ii2001

close #111

2024-08-01 07:42 UTC, Hogu59 requested changes
구현하느라 고생 많았습니다. 권한을 포함해서 해야할 게 많았는데 그래도 빠르게 진행되어 다행입니다. 몇가지 코드에 대한 수정사항 보내드리니 확인 한번 해주시면 감사하겠습니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/app/build.gradle.kts
> +    implementation(libs.volley)
volley 안쓰시면 삭제 하면 좋을 것 같습니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/app/build.gradle.kts
> +    implementation(libs.androidx.tools.core)
요건 어디에 쓰는 의존성일까요?

2024-08-01 07:42 UTC, Hogu59 commented on android/app/build.gradle.kts
> +    val okhttpVersion = "4.12.0"
따로 변수 빼기 굿 :+1:

2024-08-01 07:42 UTC, Hogu59 commented on android/app/build.gradle.kts
> +    implementation("commons-io:commons-io:2.4")
오프라인 코드리뷰에서 요거랑 conscrypt 사용하는 곳 설명 부탁드립니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/app/src/main/java/net/pengcook/android/data/remote/api/MakingRecipeService.kt
> +data class PresignedUrlResponse(
이건 여기에서만 쓰이는 data class 인가요?

2024-08-01 07:42 UTC, Hogu59 commented on android/gradle/libs.versions.toml
> +volley = { group = "com.android.volley", name = "volley", version.ref = "volley" }
volley 안 쓰니까 삭제하면 좋을듯 합니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/gradle/libs.versions.toml
> +volley = "1.2.1"
volley 안 쓰니까 삭제하면 좋을듯 합니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +        val retrofit =
추후 km 코드 활용해서 리팩토링 가능할 것 같은 코드입니다. km 코드 올라오면 참고 부탁드립니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +    private val permissionArray =
permission이 array 형태여야하는 이유가 있나요? 카메라 하나밖에 없어서요

2024-08-01 07:42 UTC, Hogu59 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +        viewModel.imageUri.observe(
observe들은 따로 함수분리해서 관리해주면 좋을 것 같습니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +    private fun onAddImageClicked() {
onAddImageClicked라고 하니 ClickListener 인터페이스를 만들어서 상속받아야할 것 같은 느낌인데, 네이밍 변경은 어떨까요? "addImage(ByCondition)" 라고 하는게 함수 네임에 대한 명확한 정보를 주는 것 같습니다.

2024-08-01 07:42 UTC, Hogu59 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +        // val action = RecipeMakingFragmentDirections.actionRecipeMakingFragmentToStepMakingFragment(File(currentPhotoPath!!).name)
제 부분이 엮여 있어서 제가 확인하고 삭제하겠습니다.

2024-08-02 01:48 UTC, ii2001 commented on android/app/build.gradle.kts
> +    implementation(libs.androidx.tools.core)
저 친구가 진짜 core라서
Lifecycle, viewmodel등 여러곳에 사용됩니다!

2024-08-02 01:49 UTC, ii2001 commented on android/app/build.gradle.kts
> +    implementation("commons-io:commons-io:2.4")
FileUtils요거 사ㅏ용해서 이미지를 올려야해서 사용합니다.

2024-08-02 01:51 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/data/remote/api/MakingRecipeService.kt
> +data class PresignedUrlResponse(
이거 아마도 이미지 업로드하는 모든 곳에서 아용할 것 같아서 나중에 나눠 놓아야 할 것 같은데 좀있다 코드리뷰때 어디로 옮길지 얘기해보시죠!

2024-08-02 01:53 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +    private val permissionArray =
나중에 추가될것을 예상해서 이렇게 구현해놨습니다

2024-08-02 01:54 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +    private val permissionArray =
추가될 가능성이 없다면 수정할 수 있겠습니다.

2024-08-02 02:03 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +    private fun onAddImageClicked() {
이것도 KM리뷰에 남겼었던 내용인데
저는 작동하는 내용이 정확히 적혀있으면 좋을 것 같다고 생각하긴 합니다.. 한번 토론해보시죠

2024-08-02 02:06 UTC, kmkim2689 requested changes
하디 이미지 전송 구현 수고 많으셨습니다! 코드 잘 작성해주셨네요~

처음 겪어보는 기술들이 많았지만 잘 이겨내는 모습을 보고 깊은 감명을 받았습니다.
몇 가지 피드백 남겨드리니 참고 부탁드리겠습니다. 오늘도 화이팅

2024-08-02 02:06 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingViewModel.kt
>  }
setValue(MutableLiveData.value) 대신 postValue를 사용해야 할 특별한 이유가 있으셨나요?

개인적으로는 이미지가 단기간에 여러 차례 업로드되어 해당 Livedata의 값이 단기간 안에 변경된다거나 이벤트가 비동기적으로 처리되어야 할 일이 없을 것 같아서 위에서 작성하신 것 처럼 .value를 통해 값을 설정하는 것이 좋을 것 같다고 생각했습니다.

2024-08-02 02:06 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingViewModel.kt
>  }
파일 분리 부탁드리겠습니다!

2024-08-02 05:13 UTC, ii2001 commented on android/app/src/main/AndroidManifest.xml
> +                android:resource="@xml/fileprovider" />
요거는 저렇게 붙여서 쓰더라고요 다들??
흠냐 어떻게할까요?

2024-08-02 05:16 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/data/datasource/makingrecipe/DefaultMakingRecipeRemoteDataSource.kt
> +    }
좋은 생각입니다! 요건 이제 백엔드랑도 얘기해보고 고치겠습니다!
에러페이지 만들면 거기로 바로 이동하게 해도 괜찮을 것 같아요

2024-08-02 05:17 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/data/datasource/makingrecipe/DefaultMakingRecipeRemoteDataSource.kt
> +}
요거 조금만 나중에 자세히 설명해주세요!

2024-08-02 06:50 UTC, Hogu59 commented on android/app/src/main/java/net/pengcook/android/presentation/making/RecipeMakingFragment.kt
> +                Toast.makeText(requireContext(), "카메라 권한이 필요합니다.", Toast.LENGTH_SHORT).show()
아직까지도? 괘씸 스택 3스택 추가요~

2024-08-02 10:35 UTC, kmkim2689 commented
LGTM

2024-08-02 10:38 UTC, kmkim2689 approved these changes

2024-08-03 05:35 UTC, Hogu59 approved these changes

2024-08-05 09:01 UTC, merged