✨ implement connection for sign in & sign up via server
woowacourse-teams/2024-pengcook pull request #144
Opened 2024-08-01 13:24 UTC by kmkim2689

* add sign in and sign up data layer for connecting via server
* add layout implementations of sign in and sign up
* add injection for network

2024-08-01 17:01 UTC, Hogu59 approved these changes
인증과 로그인 관련하여 구현하느라 고생많았습니다.
코드 양으로만 봐도 확실히 많은 노력이 들어갔다는 것이 느껴지는군요.

Fake를 활용한 테스트도 좋았습니다.
다만 확실히 코드의 양이 조금 많다보니 많은 코드를 자세히 보는 것이 생각보다 쉽지 않았던것 같습니다. 같이 있을때 말씀드렸던것처럼 이제 기술단위가 많이 남지 않았으니 짧은 pr주기도 좋을것 같다는 생각이 듭니다!

내일보시죠. 고생 많으셨습니다!

2024-08-02 01:30 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/data/datasource/auth/TokenLocalDataSource.kt
> +    val authorizationData: Flow<Authorization>
공감합니당.. 저도 써보고싶어요

2024-08-02 01:44 UTC, ii2001 requested changes

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/data/model/auth/Authorization.kt
> +data class Authorization(
https://news.hada.io/topic?id=15051

요거 참고해보는건 어떨까요

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/data/remote/api/AuthorizationService.kt
> +interface AuthorizationService {
위와 마찬가지입니다.

https://news.hada.io/topic?id=15051

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/data/util/network/NetworkResponseHandler.kt
> +abstract class NetworkResponseHandler {
인터페이스 대신 
추상화를 하신 이유가 있을까요??

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpEvent.kt
> +    data object NavigateToMain : SignUpEvent
악어의 말을 제가 이해 한건지는 잘 모르겠는데
눌렀을때 어떤 상태가 바뀌었다 이런것보다 
실제로 이뤄지는 행위에 대해서 이름을 만드는게 좋다고 생각합니다.!!

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpFragment.kt
> +    // TODO 사진 받아오는 기능 구현
사진을 받아온다는게 아직 API가 안나온건가용?

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/res/layout/fragment_onboarding.xml
> +        <import type="android.view.View" />
요거 필요한 부분인가요??

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/res/layout/fragment_sign_up.xml
> +        <import type="android.view.View" />
위와 마찬가지입니다.

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/main/res/navigation/nav_graph.xml
> +    app:startDestination="@id/onboardingFragment">
요거 나중에 마지막때 옮기는거 어떨까요 지금은 home으로 만들어놓구요!

2024-08-02 01:44 UTC, ii2001 commented on android/app/src/test/java/net/pengcook/android/presentation/onboarding/OnboardingViewModelTest.kt
> +class OnboardingViewModelTest {
저희 그냥 Junit4로 테스트 하는걸까요?

2024-08-02 07:54 UTC, ii2001 approved these changes

2024-08-03 23:28 UTC, kmkim2689 commented on android/app/build.gradle.kts
> +    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:$coroutineVersion")
반영 완료입니다!

2024-08-03 23:30 UTC, kmkim2689 commented on android/app/build.gradle.kts
> +    testImplementation("org.robolectric:robolectric:4.13")
간략히 설명하면, 유닛 테스트에서 안드로이드 API인 LiveData를 우회하여 사용하기 위해 추가한 의존성입니다.

2024-08-03 23:30 UTC, kmkim2689 commented on android/app/build.gradle.kts
> +    implementation(libs.core)
조정 완

2024-08-03 23:30 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/data/datasource/auth/AuthorizationRemoteDataSource.kt
> +    suspend fun fetchUsernameDuplication(username: String): Response<UsernameDuplicationResponse>
checkUsernameDuplication 좋아보이네요! 반영하겠습니다.

2024-08-03 23:31 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/data/datasource/auth/TokenLocalDataSource.kt
> +    val authorizationData: Flow<Authorization>
Datastore 라이브러리가 Flow 기반이라서 불가피하게 사용하게 되었네요...

2024-08-03 23:34 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpEvent.kt
> +    data object NavigateToMain : SignUpEvent
SignUpSuccessful로 변경하겠습니다.

2024-08-03 23:51 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpFragment.kt
> +    private fun showSnackBar(message: String) {
공감합니다. 스낵바를 사용할 건지 토스트를 사용할 건지 결정만 이뤄진다면 BaseFragment를 만들든 해서 조치하면 될 것 같습니다.

2024-08-03 23:53 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpViewModel.kt
> +    private val validateUsernameUseCase: ValidateUsernameUseCase = ValidateUsernameUseCase(),
사실 UseCase가 들어간 만큼 모든 것을 UseCase로 받아야 하긴 합니다... 검증을 로컬에서 처리하다 보니 UseCase를 만드는 것이 좋다고 생각해서 이렇게 만들었는데 나중에는 Repo의 작업들을 UseCase로 빼야할 것 같습니다.

2024-08-04 00:09 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpEvent.kt
> +    data object NavigateToMain : SignUpEvent
다만 리팩토링 하면서 한 가지 기준점을 잡게 되었는데
* UI 단의 작동이 직접적으로 이벤트를 발생시키는 경우, 발생한 UI 이벤트를 명시하는 네이밍(BackPressed)
* UI 단의 작동으로 서버 통신/디비 연산 등의 결과가 존재하는 경우 해당 연산 혹은 동작의 결과(SignUpSuccessful)
이렇게 사용하는 것은 어떨까요? 일단 변경은 진행해보았습니다.

2024-08-04 00:11 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpViewModelFactory.kt
> +                platformName,
반영했습니다

2024-08-04 00:40 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpViewModel.kt
> +        viewModelScope.launch {
함수 분리 해보겠습니다.

2024-08-04 00:41 UTC, kmkim2689 commented on android/app/src/main/res/layout/fragment_onboarding.xml
> +        <import type="android.view.View" />
필요 없어서 삭제하겠습니다!

2024-08-04 00:41 UTC, kmkim2689 commented on android/app/src/main/res/layout/fragment_sign_up.xml
> +        <import type="android.view.View" />
필요 없어서 삭제하겠습니다!

2024-08-04 00:42 UTC, kmkim2689 commented on android/app/src/test/java/net/pengcook/android/presentation/onboarding/OnboardingViewModelTest.kt
> +class OnboardingViewModelTest {
5가 좋을 것 같긴 한데 일단 4로 가보기로 했으니 진행해보겠습니다.

2024-08-04 00:43 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpFragment.kt
> +    // TODO 사진 받아오는 기능 구현
사진 전송 구현이 머지되면 주석처리 해제하고 구현할 계획입니다.

2024-08-04 00:43 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/data/util/network/NetworkResponseHandler.kt
> +abstract class NetworkResponseHandler {
코드가 반복적으로 사용되어 변경하였습니다.

2024-08-04 00:59 UTC, kmkim2689 commented on android/app/src/main/res/navigation/nav_graph.xml
> +    app:startDestination="@id/onboardingFragment">
넵 알겠습니다

2024-08-04 01:05 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/data/model/auth/Authorization.kt
> +data class Authorization(
Session으로 진행해보는 것은 어떨까요?

2024-08-04 01:06 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/data/remote/api/AuthorizationService.kt
> +interface AuthorizationService {
이건 추후 메소드 개수가 많아지면 분리해보겠습니다...

2024-08-04 01:14 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/presentation/signup/SignUpViewModel.kt
> +        viewModelScope.launch {
18줄로 다이어트 했습니다. 더 이상은 힘듭니다ㅋㅋㅋ

2024-08-04 01:15 UTC, kmkim2689 commented on android/app/src/main/java/net/pengcook/android/data/model/auth/Authorization.kt
> +data class Authorization(
사용되는 데이터가 접속 상태과 관련된 데이터인 것 같아 해당 네이밍으로 결정했습니다.

2024-08-05 03:55 UTC, merged