✨ like recipe and unlike
woowacourse-teams/2024-pengcook pull request #179
Opened 2024-08-05 08:53 UTC by geoje

아래 2개의 API 를 구현하였습니다.
- `GET` `/api/likes/{recipeId}`
- `POST` `/api/likes/{recipeId}`

간단한 `CRUD` 작업 정도여서 마음껏 피드백 부탁드립니다!

2024-08-05 11:36 UTC, HaiSeong requested changes
새양 수고하셨습니다! 빨리 구현해주셨네요!

다만 몇가지 필요없는 내용과 컨벤션이 맞지 않는 부분이 있어 RC 요청 드립니다!

2024-08-05 11:36 UTC, HaiSeong commented on backend/src/test/java/net/pengcook/like/controller/RecipeLikeControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
RestDocsSetting 에 포함된 내용이라
`@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)` 도 필요없을것 같아요!

2024-08-06 01:28 UTC, geoje commented on backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
> +import org.springframework.web.bind.annotation.*;
이럴수가! 언제 한번 기본 스타일로 바꾼 뒤로 까먹고 있었네요~ 와일드카드 임포트 발생하지 않도록 IDEA 설정 끝내고 코드도 바꿔두었습니다!

2024-08-06 01:37 UTC, geoje commented on backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
> +    public void toggleLike(@LoginUser UserInfo userInfo,
넵! 우선 우테코 스타일 정렬을 하니 개행이 필요없어졌긴 했습니다! 개행 컨벤션을 다시 상기시키는 기회가 되었네요!

2024-08-06 01:40 UTC, geoje commented on backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
> +        likeService.toggleLike(userInfo, recipeId);
그러네요..
API는 요청마다 항상 같은 값을 반환해야할텐데 이 API는 그렇지 못하네요..
단순히 클라이언트 요구사항을 들어주면 된다 생각했는데 그게 아니었네요!

이 부분은 하디와 얘기하여 변경해야 할 것 같네요!

2024-08-06 04:48 UTC, geoje commented on backend/src/main/java/net/pengcook/like/service/RecipeLikeService.java
> +                .orElseThrow(() -> new RecipeLikeException(HttpStatus.NOT_FOUND, "존재하지 않는 레시피 입니다."));
저도 기존의 하던 방식대로 커스텀 Exception 을 만들어서 호출하도록 변경해보았어요. `RecipeNotFoundException` 에 메세지와 코드를 모두 담을 수 있어 서비스 코드가 간결해진다는 장점이 있지만 점점 커스텀 예외 클래스가 많아진다는 단점이 있을 것 같네요~

2024-08-06 04:49 UTC, geoje commented on backend/src/test/java/net/pengcook/like/service/RecipeLikeServiceTest.java
> +@Sql(value = "/data/like.sql", executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
오! 들어가보니 정말 그렇네요~ 사용할 때 기본 값도 신경 썻어야하는데 하나 배워갑니다!! 굿~

2024-08-06 04:50 UTC, geoje commented on backend/src/test/java/net/pengcook/like/service/RecipeLikeServiceTest.java
> +class RecipeLikeServiceTest {
아하! 이전에 `@LoginUserTest` 어노테이션을사용하려다 추가해 놓은 것을 안뺏었군요! 불필요한 빈 임포트 잘 봐주셨네요~ 좋아요!!

2024-08-06 04:52 UTC, geoje commented on backend/src/test/java/net/pengcook/like/controller/RecipeLikeControllerTest.java
> +@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
헛!! 그것의 의도하고 `RestDocsSetting` 을 만들었었는데 간과해버렸네요!! 에리한 지적 굿입니다~

2024-08-06 05:31 UTC, geoje commented on backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
> +        likeService.toggleLike(userInfo, recipeId);
해당 부분은 `Service` 단에서 분리된 메서드를 `Controller` 에서 나누어 호출하도록 변경하였습니다!
`Endpoint` 를 둘로 나눌까도 생각해보았지만, 불필요한 중가일 것이라 생각되었고, 현재로써 멱등성을 지킬 수도 있게 되었습니다!

2024-08-06 06:00 UTC, HaiSeong commented on backend/src/main/java/net/pengcook/like/controller/RecipeLikeController.java
> +        likeService.toggleLike(userInfo, recipeId);
확인했습니다! 최소 리소스로 잘 만들어주셨어요! 최고최고

2024-08-06 06:01 UTC, HaiSeong approved these changes
수고하셨습니다! 새양 화이팅 오늘 pr 그만 올려주세요 ㅠㅠㅠㅠ

2024-08-06 06:41 UTC, tackyu approved these changes
LGTM입니다 새양
고생 많으셨어요!!

2024-08-06 06:42 UTC, merged