✨ implement ingredient registration
woowacourse-teams/2024-pengcook pull request #78
Opened 2024-07-24 05:11 UTC by tackyu

## 재료 등록
`IngredientService`의 `register` 메서드를 통해 재료 등록을 진행합니다.
1. Ingredient 등록
2. IngredientRecipe 등록
3. 재료가 '대체 가능'한 상태라면 IngredientSubstitution 등록 

## 검증
재료 이름 공백/null, 중복 
개별 재료에 대한 대체 재료 이름 공백/null, 중복

- #24 
- #26

2024-07-24 06:39 UTC, HaiSeong requested changes
폰드! 코드리뷰 남겼습니다!

2024-07-24 06:39 UTC, HaiSeong commented on backend/src/main/java/net/pengcook/ingredient/service/IngredientService.java
> +    private Ingredient registerIngredient(String ingredientName) {
있으면 조회해서 가져오는 분기도 있는데 메서드명을 보면 "재료를 저장한다." 라는 의미밖에 없네요.  
registerOrGetIngredient 는 어떤가요?

2024-07-24 06:39 UTC, HaiSeong commented on backend/src/main/java/net/pengcook/ingredient/repository/IngredientRepository.java
> +    Ingredient findByName(String name);
findByName 과 getByName 의 차이를 공부해보면 알아보면 좋을것 같아요.

저도 User 쪽 가서 수정해야겠네요.

find : 찾아본다. (있을 수도 있고 없을수도 있음. 없어도 예외 x, Optional로 반환이 일반적)

get : 가져온다. (있어야 한다. 없으면 예외)

2024-07-24 06:39 UTC, HaiSeong commented on backend/src/main/java/net/pengcook/ingredient/service/IngredientService.java
> +        return ingredientRepository.save(new Ingredient(name));
카테고리 코드쪽에 좋은 로직이 있어서 참고해보시면 좋을것 같아요 
```java
        Category category = categoryRepository.findByName(name)
                .orElseGet(() -> categoryRepository.save(new Category(name)));
```

2024-07-24 06:39 UTC, HaiSeong commented on backend/src/main/java/net/pengcook/ingredient/service/IngredientService.java
> +
registerSubstitution 메서드와 registerIngredientSubstitution 이 메서드를 private 보다 IngredientRecipeService와 IngredientSubstitutionService의 public 메서드로 해보는것은 어떨까요?

IngredientSubstitution을 저장하는것은 IngredientSubstitutionService의 책임인데 이걸 IngredientService가 대신 해주고 있는것 같아요. 

또한 Private 메서드라 테스트가 어려워요.

2024-07-24 06:39 UTC, HaiSeong commented on backend/src/test/java/net/pengcook/ingredient/service/IngredientServiceTest.java
> +        Recipe recipe = new Recipe(
ingredient.sql에 레시피 정보를 저장하면 불필요한 레포지토리 의존을 줄일 수 있을것 같아요.

2024-07-24 06:39 UTC, HaiSeong commented on backend/src/test/java/net/pengcook/ingredient/service/IngredientServiceTest.java
> +    @DisplayName("재료 등록")
테스트 디스플레이 네임을 컨벤션에 맞춰주세요

2024-07-24 06:51 UTC, HaiSeong commented on backend/src/main/java/net/pengcook/ingredient/domain/Ingredient.java
> +@NoArgsConstructor
`protected`로 정정합니다

2024-07-25 02:07 UTC, HaiSeong approved these changes
어제 고생 많았습니다!! 수고했습니다!

2024-07-25 02:23 UTC, hyxrxn approved these changes
잘 읽었습니다~~~
대체재료 때문에 꽤나 힘드셨겠어요
고생하셨습니다

2024-07-25 02:23 UTC, hyxrxn commented on backend/src/test/java/net/pengcook/ingredient/dto/IngredientCreateRequestTest.java
> +    @DisplayName("재료 이름에 공백 또는 null은 허용하지 않는다.")
### ✅ 테스트 코드 네이밍

- DisplayName은 꼭 사용해요.
- DisplayName
    - 성공
        - {행위}가 된다.
    - 실패
        - {상황}에 {행위}를 하면 예외가 발생한다.


재료 이름에 공백 또는 null이 입력되면 예외가 발생한다.
어떨지요

2024-07-25 02:23 UTC, hyxrxn commented on backend/src/main/java/net/pengcook/ingredient/service/IngredientService.java
> +    }
이 메서드가... 꼭 필요한가요....???
정말 몰라서 물어보는 겁니다!!!

2024-07-25 04:41 UTC, tackyu commented on backend/src/main/java/net/pengcook/ingredient/service/IngredientService.java
> +    }
가독성을 위해 생성하였습니다.
꼭 필요하진 않습니다!🥲

2024-07-25 05:37 UTC, merged